#!/bin/sh

CONFIG="${HOME}/.backup/config"

. ${CONFIG}

echo "Checking differences to first backup."
rsync -n -avz --progress "${MASTER}" "${BK1}"

echo "Checking differences to second backup."
rsync -n -avz --progress "${MASTER}" "${BK2}"
